export interface CityData {
  slug: string;
  name: string;
  region: string;
  population: number;
  description: string;
}

export const citiesData: CityData[] = [
  { slug: "kyiv", name: "Київ", region: "Київська область", population: 2884000, description: "столиця України" },
  { slug: "kharkiv", name: "Харків", region: "Харківська область", population: 1433000, description: "друге за величиною місто України" },
  { slug: "odesa", name: "Одеса", region: "Одеська область", population: 1017000, description: "перлина біля моря" },
  { slug: "dnipro", name: "Дніпро", region: "Дніпропетровська область", population: 980000, description: "промисловий центр України" },
  { slug: "donetsk", name: "Донецьк", region: "Донецька область", population: 905000, description: "індустріальне серце Донбасу" },
  { slug: "zaporizhzhia", name: "Запоріжжя", region: "Запорізька область", population: 722000, description: "місто козацької слави" },
  { slug: "lviv", name: "Львів", region: "Львівська область", population: 721000, description: "культурна столиця України" },
  { slug: "kryvyi-rih", name: "Кривий Ріг", region: "Дніпропетровська область", population: 612000, description: "найдовше місто Європи" },
  { slug: "mykolaiv", name: "Миколаїв", region: "Миколаївська область", population: 476000, description: "місто корабелів" },
  { slug: "mariupol", name: "Маріуполь", region: "Донецька область", population: 431000, description: "приморське місто" },
  { slug: "luhansk", name: "Луганськ", region: "Луганська область", population: 399000, description: "східне місто України" },
  { slug: "sevastopol", name: "Севастополь", region: "Крим", population: 393000, description: "місто-герой" },
  { slug: "vinnytsia", name: "Вінниця", region: "Вінницька область", population: 370000, description: "місто на Бузі" },
  { slug: "makiivka", name: "Макіївка", region: "Донецька область", population: 340000, description: "місто металургів" },
  { slug: "simferopol", name: "Сімферополь", region: "Крим", population: 332000, description: "столиця Криму" },
  { slug: "chernihiv", name: "Чернігів", region: "Чернігівська область", population: 285000, description: "стародавнє місто України" },
  { slug: "poltava", name: "Полтава", region: "Полтавська область", population: 283000, description: "місто Полтавської битви" },
  { slug: "kherson", name: "Херсон", region: "Херсонська область", population: 283000, description: "південна брама України" },
  { slug: "khmelnytskyi", name: "Хмельницький", region: "Хмельницька область", population: 274000, description: "місто на Поділлі" },
  { slug: "cherkasy", name: "Черкаси", region: "Черкаська область", population: 272000, description: "серце України" },
  { slug: "chernivtsi", name: "Чернівці", region: "Чернівецька область", population: 264000, description: "маленький Париж" },
  { slug: "zhytomyr", name: "Житомир", region: "Житомирська область", population: 263000, description: "місто бурштину" },
  { slug: "sumy", name: "Суми", region: "Сумська область", population: 259000, description: "північне місто України" },
  { slug: "horlivka", name: "Горлівка", region: "Донецька область", population: 241000, description: "шахтарське місто" },
  { slug: "rivne", name: "Рівне", region: "Рівненська область", population: 245000, description: "західне місто" },
  { slug: "kamianske", name: "Кам'янське", region: "Дніпропетровська область", population: 229000, description: "індустріальне місто" },
  { slug: "kropyvnytskyi", name: "Кропивницький", region: "Кіровоградська область", population: 222000, description: "центр України" },
  { slug: "ivano-frankivsk", name: "Івано-Франківськ", region: "Івано-Франківська область", population: 229000, description: "місто в Карпатах" },
  { slug: "kremenchuk", name: "Кременчук", region: "Полтавська область", population: 217000, description: "промисловий центр" },
  { slug: "ternopil", name: "Тернопіль", region: "Тернопільська область", population: 217000, description: "місто на ставі" },
  { slug: "lutsk", name: "Луцьк", region: "Волинська область", population: 215000, description: "волинська столиця" },
  { slug: "bila-tserkva", name: "Біла Церква", region: "Київська область", population: 200000, description: "місто парків" },
  { slug: "kerch", name: "Керч", region: "Крим", population: 147000, description: "найстаріше місто України" },
  { slug: "melitopol", name: "Мелітополь", region: "Запорізька область", population: 150000, description: "місто вишень" },
  { slug: "nikopol", name: "Нікополь", region: "Дніпропетровська область", population: 107000, description: "місто на Дніпрі" },
  { slug: "sloviansk", name: "Слов'янськ", region: "Донецька область", population: 106000, description: "курортне місто" },
  { slug: "uzhhorod", name: "Ужгород", region: "Закарпатська область", population: 115000, description: "найзахідніше місто України" },
  { slug: "berdiansk", name: "Бердянськ", region: "Запорізька область", population: 107000, description: "азовське курортне місто" },
  { slug: "alchevsk", name: "Алчевськ", region: "Луганська область", population: 106000, description: "металургійне місто" },
  { slug: "pavlohrad", name: "Павлоград", region: "Дніпропетровська область", population: 103000, description: "місто хіміків" },
  { slug: "severodonetsk", name: "Сєвєродонецьк", region: "Луганська область", population: 101000, description: "хімічне місто" },
  { slug: "yevpatoriia", name: "Євпаторія", region: "Крим", population: 106000, description: "кримське курортне місто" },
  { slug: "kamianets-podilskyi", name: "Кам'янець-Подільський", region: "Хмельницька область", population: 99000, description: "фортеця на скелі" },
  { slug: "lysychansk", name: "Лисичанськ", region: "Луганська область", population: 95000, description: "східне місто" },
  { slug: "kramatorsk", name: "Краматорськ", region: "Донецька область", population: 150000, description: "машинобудівне місто" },
  { slug: "ternivka", name: "Тернівка", region: "Дніпропетровська область", population: 29000, description: "промислове містечко" },
  { slug: "brovary", name: "Бровари", region: "Київська область", population: 109000, description: "київське передмістя" },
  { slug: "berdychiv", name: "Бердичів", region: "Житомирська область", population: 73000, description: "історичне місто" },
  { slug: "nizhyn", name: "Ніжин", region: "Чернігівська область", population: 66000, description: "місто огірків" },
  { slug: "mukachevo", name: "Мукачево", region: "Закарпатська область", population: 85000, description: "замкове місто" },
  { slug: "konotop", name: "Конотоп", region: "Сумська область", population: 84000, description: "залізничний вузол" },
  { slug: "uman", name: "Умань", region: "Черкаська область", population: 83000, description: "місто Софіївки" },
  { slug: "yalta", name: "Ялта", region: "Крим", population: 76000, description: "південний берег Криму" },
  { slug: "kovel", name: "Ковель", region: "Волинська область", population: 69000, description: "прикордонне місто" },
  { slug: "oleksandriia", name: "Олександрія", region: "Кіровоградська область", population: 77000, description: "промислове місто" },
  { slug: "druzhkivka", name: "Дружківка", region: "Донецька область", population: 54000, description: "донбаське місто" },
  { slug: "shostka", name: "Шостка", region: "Сумська область", population: 72000, description: "хімічне виробництво" },
  { slug: "drohobych", name: "Дрогобич", region: "Львівська область", population: 74000, description: "нафтове місто" },
  { slug: "pervomaisk", name: "Первомайськ", region: "Миколаївська область", population: 60000, description: "південне місто" },
  { slug: "kostiantynivka", name: "Костянтинівка", region: "Донецька область", population: 69000, description: "промисловий центр" },
  { slug: "izmayil", name: "Ізмаїл", region: "Одеська область", population: 70000, description: "придунайське місто" },
  { slug: "korosten", name: "Коростень", region: "Житомирська область", population: 62000, description: "давнє місто" },
  { slug: "chervonohrad", name: "Червоноград", region: "Львівська область", population: 64000, description: "шахтарське місто" },
  { slug: "stryi", name: "Стрий", region: "Львівська область", population: 59000, description: "карпатське місто" },
  { slug: "boryspil", name: "Бориспіль", region: "Київська область", population: 63000, description: "аеропортове місто" },
  { slug: "fastiv", name: "Фастів", region: "Київська область", population: 45000, description: "залізничний центр" },
  { slug: "komsomolsk", name: "Комсомольськ", region: "Полтавська область", population: 48000, description: "полтавське місто" },
  { slug: "pokrovsk", name: "Покровськ", region: "Донецька область", population: 61000, description: "східне місто" },
  { slug: "smila", name: "Сміла", region: "Черкаська область", population: 66000, description: "промисловий центр" },
  { slug: "kalush", name: "Калуш", region: "Івано-Франківська область", population: 66000, description: "місто хіміків" },
  { slug: "novovolynsk", name: "Нововолинськ", region: "Волинська область", population: 52000, description: "шахтарське місто" },
  { slug: "truskavets", name: "Трускавець", region: "Львівська область", population: 28000, description: "курортне місто" },
  { slug: "irpin", name: "Ірпінь", region: "Київська область", population: 62000, description: "місто-супутник Києва" },
  { slug: "feodosiia", name: "Феодосія", region: "Крим", population: 67000, description: "кримське курортне місто" },
  { slug: "bakhmut", name: "Бахмут", region: "Донецька область", population: 71000, description: "промислове місто" },
  { slug: "enerhodar", name: "Енергодар", region: "Запорізька область", population: 53000, description: "атомне місто" },
  { slug: "rubizhne", name: "Рубіжне", region: "Луганська область", population: 56000, description: "хімічне місто" },
  { slug: "nova-kakhovka", name: "Нова Каховка", region: "Херсонська область", population: 45000, description: "місто біля ГЕС" },
  { slug: "kozyatyn", name: "Козятин", region: "Вінницька область", population: 23000, description: "залізничний вузол" },
  { slug: "kolomyia", name: "Коломия", region: "Івано-Франківська область", population: 61000, description: "прикарпатське місто" },
  { slug: "yahotyn", name: "Яготин", region: "Київська область", population: 18000, description: "київське містечко" },
  { slug: "myrhorod", name: "Миргород", region: "Полтавська область", population: 38000, description: "курортне місто" },
  { slug: "vyshneve", name: "Вишневе", region: "Київська область", population: 37000, description: "київське передмістя" },
  { slug: "svitlovodsk", name: "Світловодськ", region: "Кіровоградська область", population: 43000, description: "промислове місто" },
  { slug: "pereyaslav", name: "Переяслав", region: "Київська область", population: 26000, description: "стародавнє місто" },
  { slug: "bucha", name: "Буча", region: "Київська область", population: 37000, description: "київське передмістя" },
  { slug: "sievierodonetsk", name: "Сіверськ", region: "Донецька область", population: 11000, description: "донбаське місто" },
  { slug: "lubny", name: "Лубни", region: "Полтавська область", population: 44000, description: "полтавське місто" },
  { slug: "horishni-plavni", name: "Горішні Плавні", region: "Полтавська область", population: 50000, description: "молоде місто" },
  { slug: "kupyansk", name: "Куп'янськ", region: "Харківська область", population: 27000, description: "залізничний центр" },
  { slug: "pryluky", name: "Прилуки", region: "Чернігівська область", population: 53000, description: "чернігівське місто" },
  { slug: "novomoskovsk", name: "Новомосковськ", region: "Дніпропетровська область", population: 70000, description: "промислове місто" },
  { slug: "syevyerodoneck", name: "Торецьк", region: "Донецька область", population: 31000, description: "шахтарське місто" },
  { slug: "chortkiv", name: "Чортків", region: "Тернопільська область", population: 28000, description: "тернопільське містечко" },
  { slug: "khartsyzk", name: "Харцизьк", region: "Донецька область", population: 57000, description: "промислове місто" },
  { slug: "saki", name: "Саки", region: "Крим", population: 24000, description: "кримський курорт" },
  { slug: "kakhovka", name: "Каховка", region: "Херсонська область", population: 35000, description: "херсонське місто" },
  { slug: "vuhlehirsk", name: "Вуглегірськ", region: "Донецька область", population: 13000, description: "шахтарське місто" },
  { slug: "tokmak", name: "Токмак", region: "Запорізька область", population: 30000, description: "запорізьке місто" },
  { slug: "marhanets", name: "Марганець", region: "Дніпропетровська область", population: 45000, description: "місто хіміків" },
  { slug: "boryslav", name: "Борислав", region: "Львівська область", population: 33000, description: "нафтове місто" },
  { slug: "okhtyrka", name: "Охтирка", region: "Сумська область", population: 47000, description: "сумське місто" },
  { slug: "sambir", name: "Самбір", region: "Львівська область", population: 34000, description: "львівське місто" },
  { slug: "netishyn", name: "Нетішин", region: "Хмельницька область", population: 32000, description: "атомне місто" },
  { slug: "kakhovka-city", name: "Гола Пристань", region: "Херсонська область", population: 13000, description: "херсонське містечко" },
  { slug: "zhovti-vody", name: "Жовті Води", region: "Дніпропетровська область", population: 40000, description: "шахтарське місто" },
  { slug: "voznesensk", name: "Вознесенськ", region: "Миколаївська область", population: 34000, description: "миколаївське місто" },
  { slug: "novohrad-volynskyi", name: "Новоград-Волинський", region: "Житомирська область", population: 55000, description: "житомирське місто" },
  { slug: "khrustalnyi", name: "Хрустальний", region: "Луганська область", population: 54000, description: "донбаське місто" },
  { slug: "romny", name: "Ромни", region: "Сумська область", population: 38000, description: "історичне місто" },
  { slug: "hlukhiv", name: "Глухів", region: "Сумська область", population: 32000, description: "давня столиця" },
  { slug: "krasnodon", name: "Краснодон", region: "Луганська область", population: 48000, description: "шахтарське місто" },
  { slug: "zhmerynka", name: "Жмеринка", region: "Вінницька область", population: 35000, description: "залізничний вузол" },
  { slug: "apostolove", name: "Апостолове", region: "Дніпропетровська область", population: 16000, description: "промислове містечко" },
  { slug: "haisyn", name: "Гайсин", region: "Вінницька область", population: 25000, description: "вінницьке місто" },
  { slug: "mohyliv-podilskyi", name: "Могилів-Подільський", region: "Вінницька область", population: 29000, description: "подільське місто" },
  { slug: "alushta", name: "Алушта", region: "Крим", population: 29000, description: "кримський курорт" },
  { slug: "shepetivka", name: "Шепетівка", region: "Хмельницька область", population: 41000, description: "залізничний центр" },
  { slug: "izium", name: "Ізюм", region: "Харківська область", population: 45000, description: "харківське місто" },
  { slug: "nova-odesa", name: "Нова Одеса", region: "Миколаївська область", population: 11000, description: "миколаївське містечко" },
  { slug: "starokostiantyniv", name: "Старокостянтинів", region: "Хмельницька область", population: 33000, description: "хмельницьке місто" },
  { slug: "vasylkiv", name: "Васильків", region: "Київська область", population: 37000, description: "київське місто" },
  { slug: "snizhne", name: "Сніжне", region: "Донецька область", population: 43000, description: "донбаське місто" },
  { slug: "chuhuiv", name: "Чугуїв", region: "Харківська область", population: 31000, description: "харківське місто" },
  { slug: "sverdlovsk", name: "Свердловськ", region: "Луганська область", population: 66000, description: "шахтарське місто" },
  { slug: "kalynivka", name: "Калинівка", region: "Вінницька область", population: 18000, description: "вінницьке містечко" },
  { slug: "starobelsk", name: "Старобільськ", region: "Луганська область", population: 16000, description: "луганське місто" },
  { slug: "ladyzhyn", name: "Ладижин", region: "Вінницька область", population: 22000, description: "енергетичне місто" },
  { slug: "varash", name: "Вараш", region: "Рівненська область", population: 41000, description: "атомне місто" },
  { slug: "dubno", name: "Дубно", region: "Рівненська область", population: 37000, description: "рівненське місто" },
  { slug: "bohuslav", name: "Богуслав", region: "Київська область", population: 16000, description: "київське містечко" },
  { slug: "pershotravensk", name: "Первомайськ", region: "Луганська область", population: 33000, description: "донбаське місто" },
  { slug: "skadovsk", name: "Скадовськ", region: "Херсонська область", population: 17000, description: "азовський курорт" },
  { slug: "stebnyk", name: "Стебник", region: "Львівська область", population: 17000, description: "курортне містечко" },
  { slug: "znamianka", name: "Знам'янка", region: "Кіровоградська область", population: 22000, description: "залізничний вузол" },
  { slug: "shakhtarsk", name: "Шахтарськ", region: "Донецька область", population: 50000, description: "шахтарське місто" },
  { slug: "yuzhnoukrainsk", name: "Южноукраїнськ", region: "Миколаївська область", population: 31000, description: "атомне місто" },
  { slug: "dzhankoi", name: "Джанкой", region: "Крим", population: 38000, description: "кримське місто" },
  { slug: "kremenets", name: "Кременець", region: "Тернопільська область", population: 21000, description: "тернопільське місто" },
  { slug: "antratsyt", name: "Антрацит", region: "Луганська область", population: 57000, description: "шахтарське місто" },
  { slug: "avdiivka", name: "Авдіївка", region: "Донецька область", population: 31000, description: "промислове місто" },
  { slug: "rovenky", name: "Ровеньки", region: "Луганська область", population: 43000, description: "донбаське місто" },
  { slug: "yenakiieve", name: "Єнакієве", region: "Донецька область", population: 77000, description: "металургійне місто" },
  { slug: "yasynuvata", name: "Ясинувата", region: "Донецька область", population: 28000, description: "залізничний вузол" },
  { slug: "pervalsk", name: "Первальськ", region: "Луганська область", population: 29000, description: "шахтарське місто" },
  { slug: "krasnoarmiisk", name: "Мирноград", region: "Донецька область", population: 47000, description: "шахтарське місто" },
  { slug: "armiansk", name: "Армянськ", region: "Крим", population: 21000, description: "промислове містечко" },
  { slug: "sudak", name: "Судак", region: "Крим", population: 16000, description: "кримський курорт" },
  { slug: "debaltseve", name: "Дебальцеве", region: "Донецька область", population: 25000, description: "залізничний вузол" },
  { slug: "stakhanov", name: "Кадіївка", region: "Луганська область", population: 74000, description: "шахтарське місто" },
  { slug: "ternivka-city", name: "Тернівка", region: "Донецька область", population: 8000, description: "донбаське містечко" },
  { slug: "torez", name: "Чистякове", region: "Донецька область", population: 64000, description: "шахтарське місто" },
  { slug: "krasyi-lyman", name: "Красний Лиман", region: "Донецька область", population: 20000, description: "донбаське місто" },
  { slug: "soledar", name: "Соледар", region: "Донецька область", population: 10000, description: "місто солі" },
  { slug: "novoazovsk", name: "Новоазовськ", region: "Донецька область", population: 11000, description: "азовське місто" },
  { slug: "svatove", name: "Сватове", region: "Луганська область", population: 17000, description: "луганське місто" },
  { slug: "irshava", name: "Іршава", region: "Закарпатська область", population: 9000, description: "закарпатське містечко" },
  { slug: "rakhiv", name: "Рахів", region: "Закарпатська область", population: 15000, description: "карпатське місто" },
  { slug: "khust", name: "Хуст", region: "Закарпатська область", population: 28000, description: "закарпатське місто" },
  { slug: "vynohradiv", name: "Виноградів", region: "Закарпатська область", population: 25000, description: "закарпатське місто" },
  { slug: "berehove", name: "Берегове", region: "Закарпатська область", population: 23000, description: "термальне місто" },
  { slug: "slavuta", name: "Славута", region: "Хмельницька область", population: 34000, description: "промислове місто" },
  { slug: "novyi-rozdil", name: "Новий Розділ", region: "Львівська область", population: 26000, description: "львівське місто" },
  { slug: "henihesk", name: "Генічеськ", region: "Херсонська область", population: 19000, description: "азовське місто" },
];

export function getCityBySlug(slug: string): CityData | undefined {
  return citiesData.find(city => city.slug === slug);
}

export function getAllCitySlugs(): string[] {
  return citiesData.map(city => city.slug);
}
